title: DBS speech SOP
description: Standard Operating Procedure (SOP) for processing DBS in ET speech data.
theme: just-the-docs

url: https://petermgrund.github.io/ddktor-sop

aux_links:
  SOP repository: https://github.com/petermgrund/ddktor-sop

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: purple
  highlight:
    color: yellow

